# Generated by Django 5.0.6 on 2024-06-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
