# Generated by Django 5.0.6 on 2024-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0004_alter_persona_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='especialidad',
            field=models.CharField(max_length=40),
        ),
    ]
