# Generated by Django 5.0.6 on 2024-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0005_alter_persona_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
    ]
