# Generated by Django 5.0.6 on 2024-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0007_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
