# Generated by Django 5.0.6 on 2024-07-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0011_rename_direccion_persona_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(default='1990/01/01'),
        ),
    ]
