# Generated by Django 5.0.6 on 2024-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0013_alter_persona_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(blank=True, default='1990-01-01', null=True),
        ),
    ]
