# Generated by Django 5.0.6 on 2024-07-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0014_alter_persona_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nac',
        ),
    ]
