# Generated by Django 5.0.6 on 2024-07-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0016_rename_barrio_persona_depto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='avatar_persona',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
