# Generated by Django 5.0.6 on 2024-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acostacesarapp', '0017_alter_persona_avatar_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
